int * copy_array(int *arr, int size);
int * add_to_array(int starting_pos, int new_element, int *arr, int size);
void print_array(int *arr, int size);
int compare(const void* num1, const void* num2);
void swap(int *a, int *b);
void shuffle_array_for_kick(int arr[], int n);
void shuffle_tsp_sol(int *arr, int size);
int * combine_two_tours_from_pos(int *arr1, int *arr2, int size, int position);
int * remove_from_array(int pos, int *arr, int size);
void write_cost_to_file(double cost, const char *filename, int append);